AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local testing for @jaypie/express adapter

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs24.x

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: docker/handler.handler
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        EntryPoints:
          - docker/handler.mjs
        External:
          - express
