AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local testing for @jaypie/express adapter

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs24.x

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.handler
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
